name: ModernDupe
version: ${version}
main: me.gregzee.moderndupe.ModernDupe
api-version: '1.20'
author: Gregzee
description: Your plugin description here.
load: POSTWORLD
depend:
  - ExcellentCrates
  - LifeStealZ

commands:
  dupe:
    aliases:
      - d
    usage: /<command> [count]
  moderndupe:
    usage: /<command> <reload>